In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data  

tensor([[1, 2],
        [3, 4]])

In [3]:
n = np.array([1,2])
torch.from_numpy(n)

tensor([1, 2])

In [4]:
x_ones = torch.ones_like(x_data)
print(f"ones: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"rand values:\n {x_rand}")

ones: 
 tensor([[1, 1],
        [1, 1]]) 

rand values:
 tensor([[0.9217, 0.6008],
        [0.3549, 0.9692]])


In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape, dtype = torch.float)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"rand \n{rand_tensor}")

rand 
tensor([[0.4643, 0.3278, 0.1656],
        [0.8897, 0.5850, 0.8185]])


In [7]:
#tensor attributes

shape = rand_tensor.shape
dtype = rand_tensor.dtype
device = rand_tensor.device
print(f"shape {shape}")
print(f"dtype {dtype}")
print(f" device {device}")

shape torch.Size([2, 3])
dtype torch.float32
 device cpu


In [103]:
import torch, torchvision
model = torchvision.models.resnet18(pretrained = True)
data = torch.rand(1,3,64,64)
labels = torch.rand(1,1000)

In [104]:
prediction = model(data)

In [105]:
loss = (prediction - labels).sum()
loss.backward()

In [106]:
loss

tensor(-506.4364, grad_fn=<SumBackward0>)

In [107]:
model.parameters()
optim = torch.optim.SGD(model.parameters(), lr = 1e-2, momentum=9e-1)

In [108]:
optim.step()